a = "a"
b = "b"

[d]
x = "d.x"
y = "d.y"

[[e]]
x = "e[0].x"
y = "e[0].y"

[[e]]
x = "e[1].x"
y = "e[1].y"

[f.A]
x = "f.A.x"

[f.B]
x = """
f.
  B.
    x
"""

[f.C]
points = [
    { x = 1, y = 1, z = 0 },
    { x = 2, y = 4, z = 0 },
    { x = 3, y = 9, z = 0 },
]